# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=20)),
                ('adminEmail', models.TextField(default='1974921044@qq.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=20)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('remainder', models.FloatField(default=0.0)),
            ],
        ),
    ]
