# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_book_bookisbn'),
        ('persons', '0003_auto_20171228_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singlePrice', models.FloatField(default=0.0)),
                ('bookNumber', models.IntegerField(default=0)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCart_book', to='books.Book')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_shoppingCart', to='persons.User')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='', max_length=100)),
                ('deliveryTime', models.CharField(default='', max_length=100)),
                ('orderState', models.IntegerField(default=0)),
                ('totalMoney', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookNumber', models.IntegerField(default=0)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shoppingRecord_book', to='books.Book')),
                ('shoppingOrder', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shopppingOrder_shoppingRecord', to='shops.ShoppingOrder')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_shoppingRecord', to='persons.User')),
            ],
        ),
    ]
