# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingorder',
            name='totalMoney',
            field=models.FloatField(default=0.0),
        ),
    ]
