# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_bookisbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookAuthor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
