# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProblem',
            fields=[
                ('questionId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('questionName', models.CharField(default='', max_length=300)),
                ('questionSolution', models.TextField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='SystemRule',
            fields=[
                ('ruleId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ruleDetail', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
