# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonproblem',
            name='questionId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemrule',
            name='ruleId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
