# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0002_auto_20180101_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrule',
            name='ruleId',
            field=models.IntegerField(default=10000000, primary_key=True, serialize=False),
        ),
    ]
